# Change these first
owner: vistaardigital # Your GitHub organization or username
repo: uptime # Your GitHub repository name

sites:
  - name: Vistaar Digital
    url: https://www.vistaardigital.com
  - name: Enablr Sales
    url: https://enablrsales.com/
  - name: Enablr Sales Admin
    url: https://app.enablrsales.com/
  - name: Activatr
    url: https://activatr.in/
  - name: Pharma Sales
    url: https://salesdashboard.enablrsales.com/
  - name: CMS Ciplamedflix
    url: https://cms.ciplamedflix.com/
  - name: Kerala GHG
    url: https://climatechange.envt.kerala.gov.in/
  - name: GEDA
    url: https://climatetracker.gujarat.gov.in/
  #- name: Vasudha USA
  #  url: https://vasudhausa.org/
  #- name: Energy Transition Platform
  #  url: https://www.energytransitionplatform.org/
  - name: GHG Platform India
    url: https://www.ghgplatform-india.org/
  - name: Africa Energy Trends
    url: https://africaenergytrends.org/
  - name: ICED Staging
    url: https://iced.showdigital.in/
  - name: EHWachs
    url: https://ehwachs.com/
  - name: Turn Valves
    url: https://turnvalves.com/
    
assignees:
  - vistaar-drane
  - vistaar-mjani
  - vistaar-moza
  - vistaar-gsalvi
  - vistaar-abalotiya
  - vistaar-bkhan
  - vistaar-pshah
  - vistaar-stondwalkar
  - vistaar-apatil
  - vistaar-arpatil

status-website:
  cname: uptime.showdigital.in
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: "Site uptime monitor and status page, powered by GitHub and Upptime."
  introMessage: Real time status data
