# Change these first
owner: vistaardigital # Your GitHub organization or username
repo: uptime # Your GitHub repository name

sites:
  - name: Vistaar Digital
    url: https://www.vistaardigital.com
  - name: Enablr Sales
    url: https://enablrsales.com/
  - name: Enablr Sales Admin
    url: https://app.enablrsales.com/
  - name: Activatr
    url: https://activatr.in/
  - name: Vasudha Power
    url: https://vasudhapower.in
  - name: Energy Transition Platform
    url: https://www.energytransitionplatform.org/
  - name: GHG Platform India
    url: https://www.ghgplatform-india.org/
  - name: Element Life
    url: https://elemntlife.com/
  - name: The Fairway Agency
    url: https://thefairwayagency.com/
assignees:
  - vistaar-drane
  - vistaar-mjani
  - vistaar-moza
  - vistaar-btuscano

status-website:
  cname: uptime.showdigital.in
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: "Site uptime monitor and status page, powered by GitHub and Upptime."
  introMessage: Real time status data
